//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext
#pragma warning disable CS1591


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: InspectionCopyModel.kt:10</p>
  /// </summary>
  public class InspectionCopyModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public ISignal<string> Start => _Start;
    [NotNull] public IViewableProperty<bool> Running => _Running;
    [NotNull] public IViewableProperty<string> Result => _Result;
    [NotNull] public IViewableProperty<string> Error => _Error;
    
    //private fields
    [NotNull] private readonly RdSignal<string> _Start;
    [NotNull] private readonly RdProperty<bool> _Running;
    [NotNull] private readonly RdProperty<string> _Result;
    [NotNull] private readonly RdProperty<string> _Error;
    
    //primary constructor
    private InspectionCopyModel(
      [NotNull] RdSignal<string> start,
      [NotNull] RdProperty<bool> running,
      [NotNull] RdProperty<string> result,
      [NotNull] RdProperty<string> error
    )
    {
      if (start == null) throw new ArgumentNullException("start");
      if (running == null) throw new ArgumentNullException("running");
      if (result == null) throw new ArgumentNullException("result");
      if (error == null) throw new ArgumentNullException("error");
      
      _Start = start;
      _Running = running;
      _Result = result;
      _Error = error;
      _Running.OptimizeNested = true;
      _Result.OptimizeNested = true;
      _Error.OptimizeNested = true;
      BindableChildren.Add(new KeyValuePair<string, object>("start", _Start));
      BindableChildren.Add(new KeyValuePair<string, object>("running", _Running));
      BindableChildren.Add(new KeyValuePair<string, object>("result", _Result));
      BindableChildren.Add(new KeyValuePair<string, object>("error", _Error));
    }
    //secondary constructor
    internal InspectionCopyModel (
    ) : this (
      new RdSignal<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString),
      new RdProperty<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => 4690292460081841852L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("InspectionCopyModel (");
      using (printer.IndentCookie()) {
        printer.Print("start = "); _Start.PrintEx(printer); printer.Println();
        printer.Print("running = "); _Running.PrintEx(printer); printer.Println();
        printer.Print("result = "); _Result.PrintEx(printer); printer.Println();
        printer.Print("error = "); _Error.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionInspectionCopyModelEx
   {
    public static InspectionCopyModel GetInspectionCopyModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("inspectionCopyModel", () => new InspectionCopyModel());
    }
  }
}
#pragma warning restore CS1591
